defaults:
  - model: tdmpc_custom


_target_: sac_gmm.rl.pretrain_play.PretrainOnPlay
_recursive_: false

batch_size: 512

# Model
model_lr: 1e-3
model_tau: 0.99

# Evaluation frequency:
eval_frequency: ${eval_frequency}

n_skill: 1
horizon: 16
pretrain_data_path: "/home/lagandua/projects/skimo_base/refining-skill-sequences/data/calvin_w_static.gz"
pretrain_train_split: 0.99
target_update_freq: 2
train_iter: 5
