defaults:
  - calvin_env: open_drawer
  # - override calvin_env/scene: calvin_scene_A

# Environment params
env_name: calvin
ee_noise: ${ee_noise}
obs_space: ${obs_space}

calvin_env:
  show_gui: ${show_gui}
