defaults:
  - setup
  - setup_single_skill
  - datamodule: calvin_ds2
  - logger: wandb

logger:
  group: gmm-eval

show_gui: false

skill_name: open_drawer
skill:
  name: ${skill_name}
  n_components: 3 # components change for RiepybdlibGMM

# Dataset params:
train: false # false to load validation dataset
goal_centered: false # this must be false during evaluation

# GMM Type
gmm_type: 2

num_rollouts: 50

# Environment params
render: false
record: true

hydra:
  run:
    dir: ${log_dir}/gmm-eval-runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/gmm-eval-runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir