defaults:
  - setup
  - callbacks: default
  - rl: pretrain_play
  - logger: wandb
  - trainer: default

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

# Env params
show_gui: false


# Experiment length
max_env_steps: 5e5

# evaluation frequency:
eval_frequency: 100
num_init_steps: 256
num_eval_episodes: 10

# Logging
logger:
  group: pretrain

hydra:
  run:
    dir: ${log_dir}/pretrain/${now:%Y_%m_%d}/${now:%H_%M_%S}
  sweep:
    dir: ${log_dir}/pretrain/${now:%Y_%m_%d}/${now:%H_%M_%S}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir