defaults:
  - setup
  - setup_single_skill
  - callbacks: default
  - datamodule: calvin_ds
  - rl: sac_gmm_mb
  - agent: sac_gmm_mb_calvin
  - logger: wandb
  - trainer: default

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

show_gui: false

# GMM params
gmm_type: 1

# Skill
skill_name: move_slider_left
skill:
  name: ${skill_name}
  max_steps: 128
  n_components: 4 # components change for RiepybdlibGMM

# Experiment length
max_env_steps: 250000

# evaluation frequency:
eval_frequency: 50
num_init_steps: 256
num_eval_episodes: 10

# Dataset params:
train: true # false to load validation dataset
goal_centered: true # this must be false during evaluation

# Visualization
render: false
record: true

model_ckpt: "logs/pretrain/2024_02_10/10_06_51/sacgmm2/lagandua_2024_02_10_10_06_51_.6416/checkpoints/epoch=199999-step=200000.ckpt"

# Logging
logger:
  group: sacgmm-mb-static

hydra:
  run:
    dir: ${log_dir}/sacgmm-train/${now:%Y_%m_%d}/${now:%H_%M_%S}
  sweep:
    dir: ${log_dir}/sacgmm-train/${now:%Y_%m_%d}/${now:%H_%M_%S}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir