defaults:
  - setup
  - skill_setup
  - callbacks: default
  - sac: sac_model
  - logger: wandb
  - trainer: default

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

# evaluation frequency:
eval_frequency: 100
num_init_steps: 2
num_eval_episodes: 20

hydra:
  run:
    dir: ${log_dir}/sac-train/${now:%Y_%m_%d}/${now:%H_%M_%S}
  sweep:
    dir: ${log_dir}/sac-train/${now:%Y_%m_%d}/${now:%H_%M_%S}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir