defaults:
  - default

name: MimicSACGMM
calvin_env: ${env}

priors_change_range: 0.0
mu_change_range: 0.08
adapt_per_episode: 4

mimic_sac_gmm: true

_target_: sac_gmm.agents.calvin.kis_gmm_agent.KISGMMAgent
_recursive_: false

