_target_: sac_gmm.rl.agent.calvin.sac_gmm_mb_calvin.CALVINSACGMM_MB_Agent
_recursive_: false

calvin_env: ${env}
datamodule: ${datamodule}

num_init_steps: ${num_init_steps}
num_eval_episodes: ${num_eval_episodes}

priors_change_range: 0.0
mu_change_range: 0.05
quat_change_range: 0.0

skill: ${skill}
gmm: ${gmm}
adapt_cov: false
mean_shift: false
adapt_per_episode: 8

exp_dir: ${exp_dir}
render: ${render}
record: ${record}
root_dir: ${root}

cem_cfg: 
  use_cem: true
  cem_iter: 6
  num_elites: 64
  num_sample_traj: 512
  num_policy_traj: 25
  cem_momentum: 0.1
  cem_temperature: 0.5
  max_std: 0.5
  min_std: 0.05
  std_step: 25000
  horizon_step: 25000
  cem_discount: 0.99