defaults:
  - default

name: SACGMM
calvin_env: ${env}

priors_change_range: 0.0
mu_change_range: 0.03
adapt_per_episode: 4

_target_: sac_gmm.agents.calvin.sac_gmm_agent.SACGMMAgent
_recursive_: false
